---
title: "RQ4"
author: "Ali Arabat"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library("scales")
library(ggplot2)
```

```{r}
RQ4_URL = "/Users/aliarabat/Documents/PhD/projects/openstack-evolution/RQs/RQ4/Files/"

df_all_dependencies<-read.csv("/Users/aliarabat/Documents/PhD/projects/openstack-evolution/Files/all_dependencies_summarized.csv")
cross_project_changes_reviewers_intersect <- read.csv(paste(RQ4_URL, "cross_project_changes_reviewers_intersect.csv", sep=""))
cross_service_changes_reviewers_intersect <- read.csv(paste(RQ4_URL, "cross_service_changes_reviewers_intersect.csv", sep=""))
same_dev_experience <- read.csv(paste(RQ4_URL, "same_dev_experience.csv", sep=""))
Same_dev_churn <- read.csv(paste(RQ4_URL, "Same_dev_churn.csv", sep=""))
Same_dev_duration <- read.csv(paste(RQ4_URL, "Same_dev_duration.csv", sep=""))
Same_dev_revisions <- read.csv(paste(RQ4_URL, "Same_dev_revisions.csv", sep=""))
Duration_reviewers <- read.csv(paste(RQ4_URL, "Duration_reviewers.csv", sep=""))
```


```{r}
p1_1<-df_all_dependencies%>%
  # mutate(service = log1p(service))%>%
ggplot() +
  geom_boxplot(aes(x=Project_type, y=Churn, fill=is_same_dev), outlier.shape = NA)+
  scale_y_continuous(trans = "log1p", breaks = c(0, 1, 10, 100, 1000))+
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "top",
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 10, color = "grey30"),
    axis.title = element_text(size = 10)
  )+
  # theme(legend.title=element_blank())+
  labs(x = "Projects", y = "Code churn", fill = "Developers")
p1_1
```


```{r}
p1_2<-df_all_dependencies[df_all_dependencies$Duration>=0,]%>%
  # mutate(service = log1p(service))%>%
ggplot() +
  geom_boxplot(aes(x=Project_type, y=Duration, fill=is_same_dev), outlier.shape = NA)+
  scale_y_continuous(trans = "log1p", breaks = c(0, 1, 10, 100, 1000))+
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "top",
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 10, color = "grey30"),
    axis.title = element_text(size = 10)
  )+
  # theme(legend.title=element_blank())+
  labs(x = "Projects", y = "Duration (hours)", fill = "Developers")
p1_2
```


```{r}
p1_3<-df_all_dependencies%>%
  # mutate(service = log1p(service))%>%
ggplot() +
  geom_boxplot(aes(x=Project_type, y=Revisions, fill=is_same_dev), outlier.shape = NA)+
  scale_y_continuous(trans = "log1p", breaks = c(0, 1, 10, 100, 1000))+
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "top",
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 10, color = "grey30"),
    axis.title = element_text(size = 10)
  )+
  # theme(legend.title=element_blank())+
  labs(x = "Projects", y = "# of revisions", fill = "Developers")
p1_3
```

```{r}
p2_1<-Same_dev_churn%>%
  # mutate(service = log1p(service))%>%
ggplot() +
  geom_boxplot(aes(x=Label, y=Churn), outlier.shape = NA)+
  scale_y_continuous(trans = "log1p", breaks = c(0, 1, 10, 100, 1000))+
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "top",
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 10, color = "grey30"),
    axis.title = element_text(size = 10)
  )+
  # theme(legend.title=element_blank())+
  labs(x = "Projects", y = "Churn")
p2_1
```

```{r}
p2_2<-Same_dev_duration%>%
  # mutate(service = log1p(service))%>%
ggplot() +
  geom_boxplot(aes(x=Label, y=Duration), outlier.shape = NA)+
  scale_y_continuous(trans = "log1p", breaks = c(0, 1, 10, 100, 1000))+
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "top",
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 10, color = "grey30"),
    axis.title = element_text(size = 10)
  )+
  # theme(legend.title=element_blank())+
  labs(x = "Projects", y = "Duration (hours)")
p2_2
```


```{r}
p2_3<-Same_dev_revisions%>%
  # mutate(service = log1p(service))%>%
ggplot() +
  geom_boxplot(aes(x=Label, y=Revisions), outlier.shape = NA)+
  scale_y_continuous(trans = "log1p", breaks = c(0, 1, 10, 100, 1000))+
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "top",
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 10, color = "grey30"),
    axis.title = element_text(size = 10)
  )+
  # theme(legend.title=element_blank())+
  labs(x = "Projects", y = "# of revisions")
p2_3
```



```{r}
# developers_cochanges_percentage <- developers_cochanges_percentage %>% 
#   dplyr::mutate(perc = Count/sum(Count),
#                 ymax = cumsum(perc),
#                 ymin = ifelse(is.na(lag(ymax)), 0, lag(ymax)))
# p1<-ggplot(developers_cochanges_percentage)+
#   geom_rect(aes(ymin = ymin, ymax = ymax, fill = Owner, xmin = 2, xmax = 4))+
#   coord_polar(theta = "y", start = 1)+
#   theme_void()+
#   xlim(c(-1, 4))+
#   geom_text(aes(x = 3, y = perc, label = paste0(round(perc*100,1), "%")), 
#                 position = position_stack(vjust = 0.5), size = 4)+
#   scale_fill_brewer(palette="Set2")
# p1
```


```{r}
p3_1<-cross_project_changes_reviewers_intersect%>%
   # mutate(Revs_intersection = log1p(Revs_intersection))%>%
  ggplot(aes(x = factor(0), y = intersect_rev)) + 
  geom_boxplot() + 
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "top",
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 9, color = "grey30"),
    axis.title = element_text(size = 10)
  )+
  labs(x = "", y = "Reviewers intersection") +
  scale_x_discrete(breaks = NULL)
p3_1
# median(cross_project_changes_reviewers_intersect$intersect_rev)
```

```{r}
p3_2<-cross_service_changes_reviewers_intersect%>%
   # mutate(Revs_intersection = log1p(Revs_intersection))%>%
  ggplot(aes(x = factor(0), y = intersect_rev)) + 
  geom_boxplot() + 
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "top",
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 9, color = "grey30"),
    axis.title = element_text(size = 10)
  )+
  labs(x = "", y = "Reviewers intersection") +
  scale_x_discrete(breaks = NULL)
p3_2
# median(cross_project_changes_reviewers_intersect$intersect_rev)
```


```{r}
p3_3<-same_dev_experience%>%
   # mutate(Revs_intersection = log1p(Revs_intersection))%>%
  ggplot() + 
  geom_boxplot(aes(x = factor(0), y = max_min), outlier.shape = NA) + 
  scale_y_continuous(trans = "log1p", breaks = c(0,1,10, 100, 1000))+
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "top",
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 9, color = "grey30"),
    axis.title = element_text(size = 10)
  )+
  labs(x = "", y = "max / min") +
  scale_x_discrete(breaks = NULL)
p3_3
median(same_dev_experience$max_min)
```

```{r}
p3_4<-same_dev_experience%>%
   # mutate(Revs_intersection = log1p(Revs_intersection))%>%
  ggplot() + 
  geom_boxplot(aes(x = factor(0), y = max), outlier.shape = NA) + 
  scale_y_continuous(trans = "log1p", breaks = c(0,1,10, 100, 1000))+
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "top",
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 9, color = "grey30"),
    axis.title = element_text(size = 10)
  )+
  labs(x = "", y = "# of changes") +
  scale_x_discrete(breaks = NULL)
p3_4
```

```{r}
p3_5<-same_dev_experience%>%
   # mutate(Revs_intersection = log1p(Revs_intersection))%>%
  ggplot() + 
  geom_boxplot(aes(x = factor(0), y = min), outlier.shape = NA) + 
  scale_y_continuous(trans = "log1p", breaks = c(0,1,10, 100, 1000))+
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "top",
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 9, color = "grey30"),
    axis.title = element_text(size = 10)
  )+
  labs(x = "", y = "# of changes") +
  scale_x_discrete(breaks = NULL)
p2_3
```

```{r}
res <- wilcox.test(same_dev_experience$min, same_dev_experience$max,
                   exact = FALSE)
res
```



```{r}
p3_6<-services_intersection%>%
   # mutate(Revs_intersection = log1p(Revs_intersection))%>%
  ggplot(aes(x = factor(0), y = Revs_intersect)) + 
  geom_boxplot() + 
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "top",
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 9, color = "grey30"),
    axis.title = element_text(size = 10)
  )+
  labs(x = "", y = "Reviewers intersection") +
  scale_x_discrete(breaks = NULL)
p3_6
```


```{r}
p4_1<-Duration_reviewers%>%
  # mutate(projects_nbr = log1p(projects_nbr))%>%
ggplot() +
  geom_boxplot(aes(x=Project_type, y=Duration, fill=Reviewer_sharing), outlier.shape = NA)+
  scale_y_continuous(trans = "log1p", breaks = c(0,1,10, 100, 1000))+
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "top",
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 9, color = "grey30"),
    axis.title = element_text(size = 10)
  )+
  # theme(legend.title=element_blank())+
  labs(x = "Projects", y = "Duration (hours)", fill = "Sharing reviewer")
p4_1
```

```{r}
res2 <- wilcox.test(df_all_dependencies[(df_all_dependencies$Project_type=="Target")&(df_all_dependencies$is_same_dev=="Same"),]$Revisions, df_all_dependencies[(df_all_dependencies$Project_type=="Target")&(df_all_dependencies$is_same_dev=="Different"),]$Revisions,
                   exact = FALSE)
res2
```


```{r}
res3 <- wilcox.test(Duration_reviewers[(Duration_reviewers$Project_type=="Target")&(Duration_reviewers$Reviewer_sharing=="At least one"),]$Duration, Duration_reviewers[(Duration_reviewers$Project_type=="Target")&(Duration_reviewers$Reviewer_sharing=="Different"),]$Duration,
                   exact = FALSE)
res3
```

