---
title: "RQ4"
author: "Ali Arabat"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library("scales")
library(ggplot2)
```

```{r}
association_rules<-read.csv("/Users/aliarabat/Documents/PhD/projects/openstack-evolution/Files/Metrics/association_rules.csv")
k_means_data<-read.csv("/Users/aliarabat/Documents/PhD/projects/openstack-evolution/RQs/RQ5_MA/k_means_data.csv")
```

```{r}
p1<-association_rules%>%
   # mutate(Revs_intersection = log1p(Revs_intersection))%>%
  ggplot(aes(x = factor(0), y = conf)) + 
  geom_boxplot() + 
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "right",
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 9, color = "grey30"),
    axis.title = element_text(size = 10)
  )+
  labs(x = "", y = "Confidence") +
  scale_y_continuous(labels = scales::percent)+
  scale_x_discrete(breaks = NULL)
# p1
median(association_rules$conf)
```

```{r}
k_means_data<-read.csv("/Users/aliarabat/Documents/PhD/projects/openstack-evolution/RQs/RQ5_MA/k_means_data.csv")
k_means_data <- k_means_data %>%
  mutate(Total_changes = log(Total_changes),
         Total_cross_project_changes = log(Total_cross_project_changes))
# Specify the number of clusters
k <- 3

# Perform k-means clustering
kmeans_result <- kmeans(k_means_data, centers = k)

# Add cluster labels to the data frame
k_means_data <- k_means_data %>%
  mutate(cluster = as.factor(kmeans_result$cluster))

# Extract the centroid coordinates
centroids <- kmeans_result$centers

# Plot the data points with cluster assignments
p2<-ggplot(k_means_data, aes(Total_changes, Total_cross_project_changes, color = cluster)) +
  geom_point(size = 2) +
   geom_point(data = as.data.frame(centroids), aes(x = Total_changes, y = Total_cross_project_changes),
             color = "black", size = 3, shape = 2) +
  scale_color_discrete(name = "Cluster") +
  theme_linedraw() +
  theme(
    panel.grid.major=element_line(colour="grey"),
    panel.grid.minor=element_line(colour="grey"),
    # panel.grid.major = element_blank(),
    # panel.grid.minor = element_blank(),
    # panel.background = element_blank(),
    legend.position = "right",
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 9, color = "grey30"),
    axis.title = element_text(size = 10)
  )+
  labs(x = "Total changes (log)", y = "Cross-project changes (log)") 
# +theme_minimal()
p2
```

```{r}
exp(kmeans_result$centers[2, "Total_changes"])
exp(kmeans_result$centers[2, "Total_cross_project_changes"])
```



