---
title: "Openstack"
output: html_document
date: "2023-01-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library("scales")
library(ggplot2)
```

## R Markdown


```{r cars}
RQ2_URL = "/Users/aliarabat/Documents/PhD/projects/openstack-evolution/RQs/RQ2/Files/"
dependencies_lag <- read.csv(paste(RQ2_URL, "all_lags.csv", sep=""))
chains_lag <- read.csv(paste(RQ2_URL, "chains_lag.csv", sep=""))
dependency_identification <- read.csv(paste(RQ2_URL, "dependency_identification.csv", sep=""))
```


```{r}
p1_1<-dependencies_lag[(dependencies_lag$lag>=0)&(dependencies_lag$is_cross=="Cross"),] %>%
  ggplot(aes(x = factor(0), y = lag)) + 
  scale_y_continuous(trans = "log1p", breaks = c(0,1,10, 100, 1000))+
  geom_boxplot() + 
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "none",
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 9, color = "grey30"),
    axis.title = element_text(size = 10)
  )+
  labs(x = "", y = "Lag (hours)") +
  scale_x_discrete(breaks = NULL)
p1_1
```

```{r}
p1_2<-chains_lag[(chains_lag$lag>=0)&(chains_lag$is_cross=="Cross"),] %>%
  ggplot(aes(x = factor(0), y = lag)) + 
  scale_y_continuous(trans = "log1p", breaks = c(0,1,10, 100, 1000))+
  geom_boxplot() + 
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "top",
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 9, color = "grey30"),
    axis.title = element_text(size = 10)
  )+
  labs(x = "", y = "Duration (hours)") +
  scale_x_discrete(breaks = NULL)
p1_2
```




```{r}
p2_1<-dependencies_lag[dependencies_lag$is_cross=="Cross",] %>%
  # mutate(nbr_changes = log1p(nbr_changes))%>%
ggplot() +
  geom_boxplot(aes(x=is_same_dev, y=lag), outlier.shape = NA)+
  scale_y_continuous(trans = "log1p", breaks = c(0,1,10, 100, 1000, 10000))+
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "none",
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 9, color = "grey30"),
    axis.title = element_text(size = 10)
  )+
  # theme(legend.title=element_blank())+
  labs(x = "Project", y = "Lag (hours)", fill = "Developer")
p2_1
```

```{r}
res1 <- wilcox.test(dependencies_lag[(dependencies_lag$is_cross=="Cross")&(dependencies_lag$is_same_dev=="Different"),]$lag, dependencies_lag[(dependencies_lag$is_cross=="Cross")&(dependencies_lag$is_same_dev=="Same"),]$lag,
                   exact = FALSE)
res1
```


```{r}
# To generate all possible Wilcox test p-valuesm just play with is_cross and same_dev according to the following values "Cross" and "Same", and "Same" and "Different", respectively.
res2 <- wilcox.test(dependency_identification[(dependency_identification$when_identified>0)&(dependency_identification$is_cross=="Cross")&(dependency_identification$same_dev=="Same"),]$when_identified, dependency_identification[(dependency_identification$when_identified>0)&(dependency_identification$is_cross=="Cross")&(dependency_identification$is_cross=="Cross")&(dependency_identification$same_dev=="Different"),]$when_identified,
                   exact = FALSE)
res2
```


```{r}
p2_2<-dependencies_lag[(dependencies_lag$lag>0)&
              !is.null(dependencies_lag$Source_service) &
               !is.null(dependencies_lag$Target_service),] %>%
  # mutate(nbr_changes = log1p(nbr_changes))%>%
ggplot() +
  geom_boxplot(aes(x=is_cross_service, y=lag, fill=is_cross_service), outlier.shape = NA)+
  scale_y_continuous(trans = "log1p", breaks = c(0,1,10, 100, 1000, 10000))+
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "none",
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 9, color = "grey30"),
    axis.title = element_text(size = 10)
  )+
  # theme(legend.title=element_blank())+
  labs(x = "Service", y = "Lag (hours)", fill = "Developer")
p2_2
```

```{r}
p4_1 <-dependency_identification[(dependency_identification$when_identified>0)&(dependency_identification$is_cross=="Cross"),] %>%
  ggplot(aes(x = factor(0), y = when_identified)) + 
  scale_y_continuous(trans = "log1p", breaks = c(0,1,10, 100, 1000))+
  geom_boxplot() + 
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "top",
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 9, color = "grey30"),
    axis.title = element_text(size = 10)
  )+
  labs(x = "", y = "Duration (hours)") +
  scale_x_discrete(breaks = NULL)
p4_1
```

```{r}
p4_2<-dependency_identification[(dependency_identification$when_identified>0)&(dependency_identification$is_cross_service=="Cross"),] %>%
  ggplot(aes(x = factor(0), y = when_identified)) + 
  scale_y_continuous(trans = "log1p", breaks = c(0,1,10, 100, 1000))+
  geom_boxplot() + 
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "top",
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 9, color = "grey30"),
    axis.title = element_text(size = 10)
  )+
  labs(x = "", y = "Duration (hours)") +
  scale_x_discrete(breaks = NULL)
p4_2
```
