---
title: "PQ"
author: "Ali Arabat"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library("scales")
library(ggplot2)
```

```{r}
DATASET_URL = "/Users/aliarabat/Documents/PhD/projects/openstack-evolution/"
dataset <- read.csv(paste(DATASET_URL, "dataset_desc.csv", sep=""))
developers <- read.csv(paste(DATASET_URL, "developers.csv", sep=""))
```


```{r}
# Reshape data using tidyr::gather
data_long <- gather(dataset[, c("project", "Contributors", "Reviewers")], key = "Variable", value = "Value", -project)

# Create a boxplot using ggplot2
p1<-ggplot(data_long, aes(x = Variable, y = Value), outlier.shape = NA) +
  geom_boxplot(fatten=.2)+
  scale_y_continuous(trans = "log1p", breaks = c(0,1,10, 100, 1000))+
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "none",
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 9, color = "grey30"),
    axis.title = element_text(size = 10)
  )+
  labs(title = "", x = "", y = "# of individuals")
p1
```


```{r}
# Reshape data using tidyr::gather
data_long <- gather(dataset[, c("project", "Merged", "Abandoned", "Open")], key = "Variable", value = "Value", -project)

# Create a boxplot using ggplot2
p2<-ggplot(data_long, aes(x = Variable, y = Value), outlier.shape = NA) +
  geom_boxplot(fatten=.2)+
  scale_y_continuous(trans = "log1p", breaks = c(0,1,10, 100, 1000))+
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "none",
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 9, color = "grey30"),
    axis.title = element_text(size = 10)
  )+
  labs(title = "", x = "", y = "# of changes")
p2
```


```{r}
# Reshape data using tidyr::gather
data_long <- gather(dataset[, c("project", "Age")], key = "Variable", value = "Value", -project)

# Create a boxplot using ggplot2
p3<-ggplot(data_long, aes(x = Variable, y = Value), outlier.shape = NA) +
  geom_boxplot(fatten=.2)+
  # scale_y_continuous(trans = "log1p", breaks = c(0,1,10, 100, 1000))+
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "none",
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 9, color = "grey30"),
    axis.title = element_text(size = 10)
  )+
  labs(title = "", x = "", y = "# of days")
p3
```

## Plot the distribution of developers
```{r}
# Reshape data using tidyr::gather
data_long <- gather(developers[, c("id", "age")], key = "Variable", value = "Value", -id)

# Create a boxplot using ggplot2
p3<-ggplot(data_long, aes(x = Variable, y = Value), outlier.shape = NA) +
  geom_boxplot(fatten=.2)+
  scale_y_continuous(trans = "log1p", breaks = c(0,1,10, 100, 1000))+
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "none",
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 9, color = "grey30"),
    axis.title = element_text(size = 10)
  )+
  labs(title = "", x = "", y = "# of changes")
p3
````