---
title: "RQ2"
author: "Ali Arabat"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(scales)
library(ggplot2)
library("ggpubr")
```

```{r}
RQ3_URL = "/Users/aliarabat/Documents/PhD/projects/openstack-evolution/RQs/RQ2/Files/"

cross_project_changes_overtime <- read.csv(paste(RQ3_URL, "cross_project_changes_overtime.csv", sep=""))
cross_service_changes_overtime <- read.csv(paste(RQ3_URL, "cross_service_changes_overtime.csv", sep=""))
cross_project_changes_across_releases <- read.csv(paste(RQ3_URL, "cross_project_changes_across_releases.csv", sep=""))
cross_service_changes_across_releases <- read.csv(paste(RQ3_URL, "cross_service_changes_across_releases.csv", sep=""))
projects_releases <- read.csv(paste(RQ3_URL, "projects_across_releases.csv", sep=""))
projects_years <- read.csv(paste(RQ3_URL, "projects_across_years.csv", sep=""))
dependent_projects_year <- read.csv(paste(RQ3_URL, "dependent_projects_year.csv", sep=""))
dependent_projects_release <- read.csv(paste(RQ3_URL, "dependent_projects_release.csv", sep=""))
dependent_projects_year <-  mutate(dependent_projects_year,year = as.character(year))
```

```{r}
projects_releases[projects_releases$type=="Archived",]
```


```{r}
give.n <- function(x){
  return(c(y = median(x)*1.05, label = length(x))) 
  # experiment with the multiplier to find the perfect position
}
```

```{r}
# p1 <-cochanges_releases[1:23,] %>%
#     # mutate(release = fct_inorder(release)) %>%
#  ggplot(aes(x=release, y=count)) +
#   geom_bar(stat="identity", color = "black", position = "dodge", alpha=0.2) +
#   geom_text(aes(label = count), vjust = -0.3, size = 3,
#             position = position_dodge(0.5)) +
#   theme_linedraw() +
#   theme(
#     panel.grid.major = element_blank(),
#     panel.grid.minor = element_blank(),
#     panel.background = element_blank(),
# 
#     axis.line = element_line(colour = "black"),
#     axis.text = element_text(size = 10, color = "grey50"),
#     # axis.line.x = element_line(angle = 45),
#     axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
#     axis.title = element_text(size = 10)
#   )+
#   labs(x = "OpenStack releases", y = "# of co-changes")+
#   scale_y_continuous(labels = label_comma(), limits =  c(0, max(cochanges_releases$count)*1.1))

p1_1<-cross_project_changes_overtime %>%
  mutate(year=paste(year, ""))%>%
  ggplot(aes(x=year, y=count)) +
  geom_segment( aes(xend=year, yend=0)) +
  geom_point( size=1.5, color="orange") +
  geom_text(aes(label = paste0("(", count, ")")), vjust = 0.3, hjust = -0.3, size = 2.5) +
  coord_flip() +
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),

    # axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 7, color = "grey50"),
    # axis.line.x = element_line(angle = 45),
    # axis.text.x = element_text(angle = 45, vjust = 0.65),
    # axis.title = element_text(size = 13)
  )+
  xlab("Periods") +
  ylab("# of cross-project changes")+
  scale_y_continuous(labels = label_number(), limits =  c(0, max(cross_project_changes_overtime$count)*1.13))
p1_1
```

```{r}
p1_2<-cross_service_changes_overtime %>%
  mutate(year=paste(year, ""))%>%
  ggplot(aes(x=year, y=count)) +
  geom_segment( aes(xend=year, yend=0)) +
  geom_point( size=1.5, color="orange") +
  geom_text(aes(label = paste0("(", count, ")")), vjust = 0.3, hjust = -0.3, size = 2.5) +
  coord_flip() +
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),

    # axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 7, color = "grey50"),
    # axis.line.x = element_line(angle = 45),
    # axis.text.x = element_text(angle = 45, vjust = 0.65),
    # axis.title = element_text(size = 13)
  )+
  xlab("Periods") +
  ylab("# of cross-service changes")+
  scale_y_continuous(labels = label_number(), limits =  c(0, max(cross_service_changes_overtime$count)*1.13))
p1_2
```


```{r}
# p2<-components_releases %>% 
#     mutate(component = fct_inorder(release)) %>%
#  ggplot(aes(x=release, y=count)) +
#   geom_bar(stat="identity", color = "black", position = "dodge", alpha=0.2) +
#   geom_text(aes(label = count), vjust = -0.3, size = 2.5,
#             position = position_dodge(0.5)) +
#   theme_linedraw() +
#   theme(
#     panel.grid.major = element_blank(),
#     panel.grid.minor = element_blank(),
#     panel.background = element_blank(),
# 
#     axis.line = element_line(colour = "black"),
#     axis.text = element_text(size = 8, color = "grey50"),
#     # axis.line.x = element_line(angle = 45),
#     axis.text.x = element_text(angle = 90, vjust = 0.45, hjust = 1),
#     axis.title = element_text(size = 10)
#   )+
#   xlab("OpenStack releases")+ 
#   ylab("# of components")+
#   scale_y_continuous(labels = label_comma(), limits =  c(0, max(components_releases$count)*1.1))

p2_1<-cross_project_changes_across_releases[5:26,] %>%
  ggplot(aes(x=release, y=count)) +
  geom_segment( aes(xend=release, yend=0)) +
  geom_point( size=1.5, color="orange") +
  geom_text(aes(label = paste0("(", count, ")")), vjust = 0.3, hjust = -0.3, size = 2.5) +
  coord_flip() +
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),

    # axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 7, color = "grey50"),
    # axis.line.x = element_line(angle = 45),
    # axis.text.x = element_text(angle = 45, vjust = 0.65),
    # axis.title = element_text(size = 13)
  )+
  xlab("Releases") +
  ylab("# cross-project changes")+
  scale_y_continuous(labels = label_comma(), limits =  c(0, max(cross_project_changes_across_releases$count)*1.1))
p2_1
```

```{r}
p2_2<-cross_service_changes_across_releases[5:26,] %>%
  ggplot(aes(x=release, y=count)) +
  geom_segment( aes(xend=release, yend=0)) +
  geom_point( size=1.5, color="orange") +
  geom_text(aes(label = paste0("(", count, ")")), vjust = 0.3, hjust = -0.3, size = 2.5) +
  coord_flip() +
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),

    # axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 7, color = "grey50"),
    # axis.line.x = element_line(angle = 45),
    # axis.text.x = element_text(angle = 45, vjust = 0.65),
    # axis.title = element_text(size = 13)
  )+
  xlab("Releases") +
  ylab("# cross-service changes")+
  scale_y_continuous(labels = label_comma(), limits =  c(0, max(cross_service_changes_across_releases$count)*1.1))
# p2_2
cross_project_changes_across_releases
```

```{r}
p3_1<-ggplot(projects_releases,aes(x=release, y = count, colour = type, group=type)) + 
    geom_line() +
    geom_point() +
    theme_linedraw() +
    theme(
      panel.grid.major=element_line(colour="grey"),
      panel.grid.minor=element_line(colour="grey"),
      legend.position='top',
      legend.justification='left',
      legend.direction='horizontal',
      axis.text.x = element_text(angle = 45, vjust = 1, hjust=0.9, size=9,colour = "black"),
          legend.text = element_text(size=10),axis.title.y = element_text(size=10,),
          axis.text.y = element_text(size=9 ,colour="black")) + 
    ylab("# of projects") + xlab("Releases")  +
    scale_colour_discrete(name="")
p3_1
```

```{r}
p3_2<-projects_years %>%
  mutate(year=paste(year, ""))%>%
  ggplot(aes(x=year, y = count, colour = type, group=type)) + 
  geom_line() +
  geom_point() +
  theme_linedraw() +
  theme(
    panel.grid.major=element_line(colour="grey"),
    panel.grid.minor=element_line(colour="grey"),
    legend.position='top',
    legend.justification='left',
    legend.direction='horizontal',
    axis.text.x = element_text(angle = 45, vjust = 0.2, hjust=0.2, size=9,colour = "black"),
          legend.text = element_text(size=10),axis.title.y = element_text(size=10,),
          axis.text.y = element_text(size=9 ,colour="black")) + 
  xlab("Years")  +  
  ylab("# of projects") + 
  scale_colour_discrete(name="")
p3_2
# sum(projects_years[projects_years$type=="Archived",]$count)
```


```{r}
x<-projects_releases[projects_releases$type=="Modified",]$count[-1]
y<-cross_project_changes_across_releases[5:26,]$count
cor.test(x=x, y=y, method="spearman")
# df<-data.frame(x=c(x), y=c(y))
# p3_2<- ggscatter(df, x = "x", y = "y",
#    add = "reg.line",  # Add regressin line
#    add.params = list(color = "blue", fill = "lightgray"), # Customize reg. line
#    conf.int = TRUE # Add confidence interval
#    )+ stat_cor(method = "pearson", label.x = 3, label.y = 30)
# p3_2
```

```{r}
dependent_projects_year = dependent_projects_year[dependent_projects_year$dependent_projects>0,]
dependent_projects_year <-  mutate(dependent_projects_year,year = as.character(year))
dataMedian0 <- summarise(group_by(dependent_projects_year, year), MD = median(dependent_projects))
p4_1<-dependent_projects_year %>%
ggplot() +
  geom_boxplot(aes(x=year, y=dependent_projects, fill=dependent_projects), outlier.shape = NA)+
  scale_y_continuous(trans = "log1p", breaks = c(0,1,10, 100, 1000))+
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "none",
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 8, color = "grey30"),
    axis.text.x = element_text(angle = 45, vjust = 0.4, hjust=0.5),
    axis.title = element_text(size = 10.5)
  )+
  geom_text(data = dataMedian0, aes(year, MD, label = MD), 
              position = position_dodge(width = 0.8), size = 3, vjust = -.9)+
  # theme(legend.title=element_blank())+
  labs(x = "Periods", y = "# of dependent projects", fill = "Developer")
p4_1
```

```{r}
dependent_projects_release = dependent_projects_release[dependent_projects_release$dependent_projects!=-1,]
dataMedian1 <- summarise(group_by(dependent_projects_release, release), MD = median(dependent_projects))
p4_2<-dependent_projects_release %>%
  # mutate(year = as.character(year))%>%
ggplot() +
  geom_boxplot(aes(x=release, y=dependent_projects, fill=dependent_projects), outlier.shape = NA)+
  scale_y_continuous(trans = "log1p", breaks = c(0,1,10, 100, 1000))+
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "none",
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 8, color = "grey30"),
    axis.text.x = element_text(angle = 90, vjust = 0.4, hjust=1),
    axis.title = element_text(size = 10.5)
  )+
  geom_text(data = dataMedian1, aes(release, MD, label = MD), 
              position = position_dodge(width = 0.8), size = 1.8, vjust = -.7)+
  # stat_summary(fun.data = give.n, aes(x=release, y=dependent_projects),vjust = -1, size=3.5, geom = "text", fun = "mean",
  #                  position = position_dodge(width = 0.75))+
  # theme(legend.title=element_blank())+
  labs(x = "Releases", y = "# of dependent projects", fill = "Developer")
p4_2
```